KitchenBundle\Entity\Country:
    exclusion_policy: ALL
    properties : 
        id:
            expose:  true
            groups: [country, chef, userDetails]
        name :
            expose : true
            groups: [country, chef, userDetails]
