KitchenBundle\Entity\Plate:
    exclusion_policy: ALL
    properties : 
        id:
            expose:  true
            groups: [chefplates, plate, plates]
        name :
            expose : true
            groups: [chefplates, plate, requestDetails, plates]
        isHot :
            expose : true
            groups: [chefplates, plate]
        price :
            expose : true
            groups: [chefplates, plate]
        image :
            expose : true
            groups: [chefplates, plate]
            accessor:
                  getter: getFullImagePath
        description :
            expose : true
            groups: [chefplates, plate]
        gallery :
            expose : true
            groups: [chefplates, plate]