KitchenBundle\Entity\User:
    exclusion_policy: ALL
    properties : 
        id :
            expose:  true
            groups: [chefs, chefplates, chef, userDetails]
        name :
            expose : true
            groups: [chefs, chefplates, chef, myOrders, userDetails]
        image :
            expose : true
            groups: [chefs, chefplates, chef]
        rate :
            expose : true
            groups: [chefs, chef]
        notes :
            expose : true
            groups: [chefplates, chef]
        deliveryNotes :
            expose : true
            groups: [chefplates, chef]
        inHoliday :
            expose : true
            groups: [chefplates, chef]
        plates :
            expose : true
            groups: [chefplates]
        city :
            expose : true
            groups: [chef]
        mobile :
            expose : true
            groups: [userDetails]
        email :
            expose : true
            groups: [userDetails]
        username :
            expose : true
            groups: [userDetails]
        lat :
            expose : true
            groups: [userDetails]
        lng :
            expose : true
            groups: [userDetails]