KitchenBundle\Entity\City:
    exclusion_policy: ALL
    properties : 
        id:
            expose:  true
            groups: [cities, chef, userDetails]
        name :
            expose : true
            groups: [cities, chef, userDetails]
        country :
            expose : true
            groups: [chef]
