KitchenBundle\Entity\User:
    exclusion_policy: ALL
    properties : 
        id :
            expose:  true
            groups: [chefs, chefplates, chef, userDetails]
        name :
            expose : true
            groups: [chefs, chefplates, chef, myOrders, userDetails, myRequests, chefComments]
        image :
            expose : true
            groups: [chefs, chefplates, chef, userDetails]
            accessor:
                  getter: getFullImagePath
        rate :
            expose : true
            groups: [chefs, chef]
        notes :
            expose : true
            groups: [chefplates, chef, userDetails]
        deliveryNotes :
            expose : true
            groups: [chefplates, chef, userDetails]
        inHoliday :
            expose : true
            groups: [chefplates, chef, userDetails]
        plates :
            expose : true
            groups: [chefplates]
        city :
            expose : true
            groups: [chef, userDetails]
        country :
            expose : true
            groups: [chef, userDetails]
        mobile :
            expose : true
            groups: [userDetails, requestDetails]
        email :
            expose : true
            groups: [userDetails]
        username :
            expose : true
            groups: [userDetails]
        lat :
            expose : true
            groups: [userDetails]
        lng :
            expose : true
            groups: [userDetails]