KitchenBundle\Entity\Request:
    exclusion_policy: ALL
    properties : 
        id:
            expose:  true
            groups: [myOrders, myRequests, requestDetails]
        totalPrice :
            expose : true
            groups: [myOrders]
        status :
            expose : true
            groups: [myOrders]
        chef :
            expose : true
            groups: [myOrders]
        user :
              expose : true
              groups: [myRequests, requestDetails]
        deliveryTime :
            expose : true
            groups: [requestDetails]
        deliveryDate :
            expose : true
            groups: [requestDetails]
        userLat :
            expose : true
            groups: [requestDetails]
        userLng :
            expose : true
            groups: [requestDetails]
        requestdetails :
              expose : true
              groups: [requestDetails]
