KitchenBundle\Utils\APIResponse:
    properties : 
        status:
            groups: ["apiResponse"]
        data:
            groups: ["apiResponse"]
        error:
            groups: ["apiResponse"]
            