services:
    category_admin:
        class: AdminBundle\Admin\CategoryAdmin
        arguments: [~, KitchenBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category} 
            
    country_admin:
        class: AdminBundle\Admin\CountryAdmin
        arguments: [~, KitchenBundle\Entity\Country, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Country}    
            
    city_admin:
        class: AdminBundle\Admin\CityAdmin
        arguments: [~, KitchenBundle\Entity\City, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: City}        
            
    user_admin:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, KitchenBundle\Entity\User, AdminBundle:User]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User} 
            
    chef_admin:
        class: AdminBundle\Admin\ChefAdmin
        arguments: [~, KitchenBundle\Entity\User, AdminBundle:Chef]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Chef} 
            
    plate_admin:
        class: AdminBundle\Admin\PlateAdmin
        arguments: [~, KitchenBundle\Entity\Plate, AdminBundle:Plate]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Plate}        
            
    rate_admin:
        class: AdminBundle\Admin\RateAdmin
        arguments: [~, KitchenBundle\Entity\Rating, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Rate} 
            
    request_admin:
        class: AdminBundle\Admin\RequestAdmin
        arguments: [~, KitchenBundle\Entity\Request, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Request}
            
    request_details_admin:
        class: AdminBundle\Admin\RequestDetailsAdmin
        arguments: [~, KitchenBundle\Entity\RequestDetails, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Request Details}          