<?php

namespace KitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GallaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GallaryRepository extends EntityRepository
{
}
