<?php

namespace KitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateRepository extends EntityRepository
{
}
