<?php

namespace KitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestDetailsRepository extends EntityRepository
{
}
