<?php

namespace KitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository {

    public function checkRequests($time) {
        $query = $this->getEntityManager()
                        ->createQuery('
            Update KitchenBundle:Request r
            set r.status = :newstatus
            WHERE r.createdAt < :time and r.status = :status
            ')->setParameters(array('newstatus' => 2, 'status' => 0, 'time' => $time));
        return $query->execute();
    }

}
