kitchen_api:
    type: rest
    prefix: /api
    resource: "@KitchenBundle/Resources/config/routing/api.yml" 
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc    
